### ISSUE TITLE
ignorePatterns not respected? 

### ISSUE THREAD

**Issue by jasikpark** [celinekurpershoek/link-checker#16]
I have `ignorePatterns: "github,google,twitter"` in my config, but I got errors from twitter anyways (twitter is sniffing the user agent and returns a 400 now).

[logs.txt](https://github.com/celinekurpershoek/link-checker/files/5791781/logs.txt)

**Comment by villesundell** [comment]
@jasikpark It seems that this issue is fixed in `master` but not in `v1.0.1`. I was able to fix this issue by using `uses: celinekurpershoek/link-checker@37818c3d3586584d04f1a989ac23545adf7a9487` in my `action.yml` (you could also use `celinekurpershoek/link-checker@master`). Maybe @celinekurpershoek could make a release for the current `master`?

**Comment by celinekurpershoek** [comment]
@villesundell Fixed in v1.0.2
Kinda lost track of this repo 😅
